# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

# trigger:
#   - master

stages:
- stage: BuildAndPublish
  variables:
    NUGET_PACKAGES: $(Pipeline.Workspace)/packages
  pool:
    vmImage: 'ubuntu-latest'
  jobs:  
  - job: BuildAndPublish
    steps:
    # - task: Cache@2
    #   displayName: Cache nuget packages
    #   inputs:
    #     key: 'paket | paket.lock'
    #     path: $(NUGET_PACKAGES)
    - task: Bash@3
      displayName: Setup pulumi
      inputs:
        targetType: inline
        script: |
          curl -fsSL https://get.pulumi.com | bash
          export PATH=$PATH:$HOME/.pulumi/bin
          echo "##vso[task.setvariable variable=path]$PATH"
          pulumi login
      env:
        PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
        
    - task: Bash@3
      displayName: Build and publish docker container(s)
      inputs:
        targetType: inline
        script: |
          make publish
    # env:
    #   PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
      # ARM_CLIENT_SECRET: $(arm.client.secret)
      # ARM_SUBSCRIPTION_ID: $(arm.subscription.id)
      # ARM_CLIENT_ID: $(arm.client.id)
      # ARM_TENANT_ID: $(arm.tenant.id)
- stage: DeployDev
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: DeployToDev
    displayName: Deploy Dev
    # creates an environment if it doesn't exist
    environment: 'sweetspot-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          # - task: Cache@2
          #   displayName: Cache nuget packages
          #   inputs:
          #     key: 'paket | paket.lock'
          #     path: $(NUGET_PACKAGES)
          - task: Bash@3
            displayName: Setup pulumi
            inputs:
              targetType: inline
              script: |
                curl -fsSL https://get.pulumi.com | bash
                export PATH=$PATH:$HOME/.pulumi/bin
                echo "##vso[task.setvariable variable=path]$PATH"
                pulumi login
                echo "==> Which AZ?"
                which az
                curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                echo "==> Which AZ?"
                which az
#                az login --service-principal -u <app-url> -p <password-or-cert> --tenant <tenant>
            env:
              PULUMI_ACCESS_TOKEN: $(pulumi.access.token)            
          # - task: AzureCLI@2
          #   displayName: Deploy dev
          #   inputs:
          #     azureSubscription: 65b5e624-0000-46fc-8835-a8b35b449321
          #     scriptType: bash
          #     scriptLocation: inlineScript
          #     inlineScript: |
          #       echo "==> Which AZ?"
          #       which az
          #       az account 
          #       echo "==> This one!"
          #       echo "==> Which pulumi?!"
          #       which pulumi
          #       echo "==> This one"
          #       make deploy
          - task: Bash@3
            displayName: Deploy dev
            inputs:
              targetType: inline
              script: |
                echo "==> Which AZ?"
                which az
                az account 
                echo "==> This one!"
                make deploy
