# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
  - master

jobs:  
- job: BuildAndPublish

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:

    # ADD CACHE


  - task: Bash@3
    inputs:
      targetType: inline
      script: |
        curl -fsSL https://get.pulumi.com | bash
        export PATH=$PATH:$HOME/.pulumi/bin
        echo "##vso[task.setvariable variable=path]$PATH"
        pulumi login
    env:
      PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
      
  - task: Bash@3
    inputs:
      targetType: inline
      script: |
        pulumi --help
#        curl -fsSL https://get.pulumi.com | bash
#        export PATH=$PATH:$HOME/.pulumi/bin
#        pulumi login
#        make publish
    env:
      PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
      # ARM_CLIENT_SECRET: $(arm.client.secret)
      # ARM_SUBSCRIPTION_ID: $(arm.subscription.id)
      # ARM_CLIENT_ID: $(arm.client.id)
      # ARM_TENANT_ID: $(arm.tenant.id)