# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

# trigger:
#   - master

stages:
- stage: BuildAndPublish
  jobs:  
  - job: BuildAndPublish

    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: Bash@3
      displayName: Setup pulumi
      inputs:
        targetType: inline
        script: |
          curl -fsSL https://get.pulumi.com | bash
          export PATH=$PATH:$HOME/.pulumi/bin
          echo "##vso[task.setvariable variable=path]$PATH"
          pulumi login
      env:
        PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
        
    - task: Bash@3
      displayName: Build and publish docker container(s)
      inputs:
        targetType: inline
        script: |
          make publish
    # env:
    #   PULUMI_ACCESS_TOKEN: $(pulumi.access.token)
      # ARM_CLIENT_SECRET: $(arm.client.secret)
      # ARM_SUBSCRIPTION_ID: $(arm.subscription.id)
      # ARM_CLIENT_ID: $(arm.client.id)
      # ARM_TENANT_ID: $(arm.tenant.id)
- stage: DeployDev
  jobs:
  - deployment: DeployToDev
    displayName: Deploy Dev
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 'sweetspot-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Bash@3
            displayName: Setup pulumi
            inputs:
              targetType: inline
              script: |
                curl -fsSL https://get.pulumi.com | bash
                export PATH=$PATH:$HOME/.pulumi/bin
                echo "##vso[task.setvariable variable=path]$PATH"
                pulumi login
            env:
              PULUMI_ACCESS_TOKEN: $(pulumi.access.token)            
          - task: Bash@3
            displayName: Deploy dev
            inputs:
              targetType: inline
              script: |
                echo "==> Deploying"
                ls -la
                pwd
                make deploy