USE sweetdb

DROP TABLE IF EXISTS OrderLine;
DROP TABLE IF EXISTS [Order];
DROP TABLE IF EXISTS [Customer];


CREATE TABLE Customer (
    CustomerId NVARCHAR PRIMARY KEY CLUSTERED,
    FirstName NVARCHAR NOT NULL,
    LastName NVARCHAR NOT NULL
)

CREATE TABLE [Order] (
    OrderId NVARCHAR PRIMARY KEY CLUSTERED,
    OrderDate DATETIMEOFFSET,
    CustomerId NVARCHAR FOREIGN KEY REFERENCES Customer(CustomerId) NOT NULL
);

CREATE TABLE OrderLine (
    OrderLineId NVARCHAR PRIMARY KEY CLUSTERED,
    Item NVARCHAR NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL NOT NULL,
    OrderId NVARCHAR FOREIGN KEY REFERENCES [Order](OrderId) NOT NULL
);